Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -32,41 +32,54 @@ jobs:
       - name: Checkout Source Code
         uses: actions/checkout@v4
 
-      - name: Debug Environment Variables
+      - name: Debug Directory and Variables
         run: |
+          echo "Debugging Directory and Variables:"
           echo "AWS_REGION=$AWS_REGION"
           echo "BUCKET_TF_STATE=$BUCKET_TF_STATE"
           echo "Directory Contents:"
-          ls -l ./terraform
+          ls -l
 
-      - name: Setup Terraform with Specified Version
+      - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.6.3
 
-      - name: Terraform Init
+      - name: Initialize Terraform
         id: init
         run: |
+          echo "Initializing Terraform Backend"
           terraform init -backend-config="bucket=$BUCKET_TF_STATE" \
                          -backend-config="region=$AWS_REGION"
+        continue-on-error: true
 
-      - name: Terraform Format Check
+      - name: Validate Terraform Init
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Terraform Init failed. Exiting."
+            exit 1
+          fi
+
+      - name: Check Terraform Format
         id: fmt
         run: terraform fmt -check
 
-      - name: Terraform Validate
+      - name: Validate Terraform Code
         id: validate
         run: terraform validate
 
       - name: Terraform Plan
         id: plan
         run: |
+          echo "Running Terraform Plan"
           terraform plan -no-color -input=false -out planfile
-        continue-on-error: false
+        continue-on-error: true
 
-      - name: Check Terraform Plan File
+      - name: Check Terraform Plan
         run: |
           if [ ! -f planfile ]; then
-            echo "Terraform plan file was not created. Exiting."
+            echo "Terraform Plan failed or planfile not created."
             exit 1
+          else
+            echo "Terraform Plan succeeded."
           fi
