Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -54,11 +54,13 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -input=false -out planfile
+        run: |
+          terraform plan -no-color -input=false -out planfile || echo $? > plan_exit_code
         continue-on-error: true
 
       - name: Check Terraform Plan Status
-        if: failure()
         run: |
-          echo "Terraform plan failed, review the error."
-          exit 1
+          if [ -f plan_exit_code ]; then
+            echo "Terraform plan failed with errors. Exiting."
+            exit 1
+          fi
